name: push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: ./mvnw spotless:check verify -B
    - name: SonarCloud Scan
      run: |
        ./mvnw sonar:sonar \
          -Dsonar.projectKey=test-semantic-release \
          -Dsonar.organization=quike-github \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  release:
      name: Release
      runs-on: ubuntu-18.04
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Setup Node.js
          uses: actions/setup-node@v2.1.1
          with:
            node-version: 12
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_TOKEN }}
          run: npx semantic-release@17